from django.urls import path
from . import views, dashboard2_utils, cockpit_utils, wireframe_utils, dashboard_service

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard', views.sales_cockpit, name='sales_cockpit'),
    path('dashboard/', views.sales_cockpit, name='sales_cockpit_slash'),
    path('dashboard2', views.dashboard2, name='dashboard2'),
    path('dashboard2/', views.dashboard2, name='dashboard2_slash'),
    path('dashboard3', views.sales_cockpit3, name='sales_cockpit3'),
    path('dashboard3/', views.sales_cockpit3, name='sales_cockpit3_slash'),
    path('wireframe/', views.wireframe, name='wireframe'),
    path('api/process/', cockpit_utils.process_file, name='process_file'),
    path('api/reapply-filters/', cockpit_utils.reapply_filters, name='reapply_filters'),
    path('api/custom-chart/', cockpit_utils.custom_chart, name='custom_chart'),
    path('api/filter-values/', cockpit_utils.filter_values, name='filter_values'),
    path('api/wireframe/generate/', wireframe_utils.wireframe_generate, name='wireframe_generate'),
    path('api/wireframe/add-artifact/', wireframe_utils.wireframe_add_artifact, name='wireframe_add_artifact'),
    path('api/dashboard/upload/', cockpit_utils.sales_cockpit_upload, name='sales_cockpit_upload'),
    path('api/dashboard/metadata/', cockpit_utils.sales_cockpit_metadata, name='sales_cockpit_metadata'),
    path('api/dashboard/column-mapping/', cockpit_utils.sales_cockpit_column_mapping, name='sales_cockpit_column_mapping'),
    path('api/dashboard/databricks-init/', cockpit_utils.sales_cockpit_databricks_init, name='sales_cockpit_databricks_init'),
    path('api/dashboard/data/', cockpit_utils.sales_cockpit_data, name='sales_cockpit_data'),
    path('api/dashboard/custom-chart/', cockpit_utils.sales_cockpit_custom_chart, name='sales_cockpit_custom_chart'),
    path('api/dashboard2/upload/', dashboard2_utils.dashboard2_upload, name='dashboard2_upload'),
    path('api/dashboard2/data/', dashboard2_utils.dashboard2_data, name='dashboard2_data'),
    path('api/dashboard/save/', dashboard_service.dashboard_save, name='dashboard_save'),
    path('api/dashboard/history/', dashboard_service.dashboard_history, name='dashboard_history'),
    path('api/dashboard/history/<uuid:dashboard_id>/', dashboard_service.dashboard_history_detail, name='dashboard_history_detail'),
]
