# Generated by Django 5.2.7 on 2026-03-23 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dashboard_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('filters_json', models.TextField(default='{}')),
                ('meta_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail_hint', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
